name: multi_cam_example
description: Demonstrates how to use the multi_cam plugin.

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  multi_cam:
    path: ../
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true