name: multi_cam
description: Plugin to access both front and back cameras on Android & iOS. 
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.solobits.multi_cam
        pluginClass: MultiCamPlugin
      ios:
        pluginClass: MultiCamPlugin
